version: 2
updates:
  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: "/**;!/**/*Tests*/**/<anything>.(cs|vb|fs)proj"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
